spring:
  application:
    name: booker-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:booker_db}
    username: ${DB_USER:booker_user}
    password: ${DB_PASSWORD:booker_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 'validate' in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1